docker-wordpress-nginx:
  ports:
  - 80:80/tcp
  tty: false
  image: eugeneware/docker-wordpress-nginx
  stdin_open: false
lb:
  image: rancher/load-balancer-service
  ports:
  - 80       # orly?
  - 82:81    # 82 and by default forward private port 81 using HTTP
  - 9999/tcp # 9999 using TCP and not HTTP
  labels:
    # Put load balancer containers on hosts with label lb=true
    - "io.rancher.scheduler.affinity:host_label=lb=true"
    # Requests to http://app.example.com/foo should be routed to web over port 8000
    - "io.rancher.loadbalancer.target.web=8000:app.example.com/foo"
    # Requests to http://app.example.com should be routed to web2 over port 8000
    - "io.rancher.loadbalancer.target.web2=8000:app.example.com"
    # Requests routed to web2 should go to port 8000, overriding the default configuration
    # of 80:81
    - "io.rancher.loadbalancer.target.web3=80"
